apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-with-timeout
spec:
  backoffLimit: 5
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo uname from the Kubernetes cluster
          restartPolicy: OnFailure
